clc; close all; 
tic;
wolves = imread('wolves.png'); 
color_space = input('Which color space you want to consider\na. RGB\nb. Grayscale\nc. HSV\nd. La*b*\n', 's');
% sel_col_spc = select_color_space(color_space, wolves);
% disp_images(wolves, wolves_gray, wolves_hsv, wolves_lab);
% figure; 
% disp_og_hist(wolves, wolves_gray, wolves_hsv, wolves_lab);
neighbor_type = input('Which neighbor type you want to consider\na. 4 - Neighbors\nb. 8 - Neighbors\n'); 
[diff1, diff2] = calculate_diff(wolves, color_space, neighbor_type);
figure;
visualize_diff_hist(diff1, diff2);toc;